// ============================================
// FinTrace - Seed Data
// ============================================

import type { Category, AppSettings } from '../types';
import { CategoryType, generateId } from '../types';

// ============================================
// Default Expense Categories
// ============================================

export const defaultExpenseCategories: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  // Food & Dining
  {
    id: generateId(),
    name: 'Food & Dining',
    type: CategoryType.EXPENSE,
    icon: '🍽️',
    color: '#FF6B6B',
    keywords: ['food', 'restaurant', 'dining', 'lunch', 'dinner', 'breakfast', 'cafe', 'swiggy', 'zomato', 'hotel'],
    merchantPatterns: ['swiggy', 'zomato', 'uber eats', 'dominos', 'pizza', 'mcdonalds', 'kfc', 'burger'],
    isSystem: true,
    isArchived: false,
    sortOrder: 1,
  },
  {
    id: generateId(),
    name: 'Groceries',
    type: CategoryType.EXPENSE,
    icon: '🛒',
    color: '#4ECDC4',
    keywords: ['grocery', 'groceries', 'vegetables', 'fruits', 'kirana', 'supermarket', 'bigbasket', 'zepto', 'blinkit'],
    merchantPatterns: ['bigbasket', 'zepto', 'blinkit', 'dmart', 'reliance fresh', 'more', 'spencer'],
    isSystem: true,
    isArchived: false,
    sortOrder: 2,
  },
  // Transport
  {
    id: generateId(),
    name: 'Transport',
    type: CategoryType.EXPENSE,
    icon: '🚗',
    color: '#45B7D1',
    keywords: ['transport', 'travel', 'uber', 'ola', 'auto', 'taxi', 'metro', 'bus', 'train', 'petrol', 'fuel', 'diesel'],
    merchantPatterns: ['uber', 'ola', 'rapido', 'indian oil', 'hp', 'bharat petroleum', 'irctc', 'metro'],
    isSystem: true,
    isArchived: false,
    sortOrder: 3,
  },
  {
    id: generateId(),
    name: 'Fuel',
    type: CategoryType.EXPENSE,
    icon: '⛽',
    color: '#F39C12',
    keywords: ['petrol', 'diesel', 'fuel', 'gas', 'cng'],
    merchantPatterns: ['indian oil', 'hp', 'bharat petroleum', 'shell', 'reliance petrol'],
    isSystem: true,
    isArchived: false,
    sortOrder: 4,
  },
  // Shopping
  {
    id: generateId(),
    name: 'Shopping',
    type: CategoryType.EXPENSE,
    icon: '🛍️',
    color: '#9B59B6',
    keywords: ['shopping', 'amazon', 'flipkart', 'myntra', 'clothes', 'fashion', 'shoes'],
    merchantPatterns: ['amazon', 'flipkart', 'myntra', 'ajio', 'nykaa', 'meesho', 'shopsy'],
    isSystem: true,
    isArchived: false,
    sortOrder: 5,
  },
  {
    id: generateId(),
    name: 'Electronics',
    type: CategoryType.EXPENSE,
    icon: '📱',
    color: '#3498DB',
    keywords: ['electronics', 'mobile', 'phone', 'laptop', 'computer', 'gadget', 'croma', 'reliance digital'],
    merchantPatterns: ['croma', 'reliance digital', 'vijay sales', 'apple'],
    isSystem: true,
    isArchived: false,
    sortOrder: 6,
  },
  // Bills & Utilities
  {
    id: generateId(),
    name: 'Bills & Utilities',
    type: CategoryType.EXPENSE,
    icon: '📄',
    color: '#1ABC9C',
    keywords: ['bill', 'utility', 'electricity', 'water', 'gas', 'internet', 'broadband', 'wifi', 'postpaid'],
    merchantPatterns: ['airtel', 'jio', 'vodafone', 'bses', 'tata power', 'adani', 'mahanagar gas'],
    isSystem: true,
    isArchived: false,
    sortOrder: 7,
  },
  {
    id: generateId(),
    name: 'Mobile & Internet',
    type: CategoryType.EXPENSE,
    icon: '📶',
    color: '#00CEC9',
    keywords: ['mobile', 'recharge', 'internet', 'broadband', 'wifi', 'data', 'postpaid', 'prepaid'],
    merchantPatterns: ['airtel', 'jio', 'vodafone', 'vi', 'bsnl', 'act fibernet'],
    isSystem: true,
    isArchived: false,
    sortOrder: 8,
  },
  // Housing
  {
    id: generateId(),
    name: 'Rent',
    type: CategoryType.EXPENSE,
    icon: '🏠',
    color: '#E17055',
    keywords: ['rent', 'house rent', 'pg', 'hostel', 'accommodation'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 9,
  },
  {
    id: generateId(),
    name: 'Society Maintenance',
    type: CategoryType.EXPENSE,
    icon: '🏢',
    color: '#FDCB6E',
    keywords: ['maintenance', 'society', 'apartment', 'complex', 'association'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 10,
  },
  {
    id: generateId(),
    name: 'Home & Living',
    type: CategoryType.EXPENSE,
    icon: '🪴',
    color: '#00B894',
    keywords: ['home', 'furniture', 'decor', 'appliance', 'ikea', 'pepperfry', 'urban ladder'],
    merchantPatterns: ['ikea', 'pepperfry', 'urban ladder', 'hometown', 'godrej'],
    isSystem: true,
    isArchived: false,
    sortOrder: 11,
  },
  // Health
  {
    id: generateId(),
    name: 'Health & Medical',
    type: CategoryType.EXPENSE,
    icon: '🏥',
    color: '#E74C3C',
    keywords: ['health', 'medical', 'medicine', 'doctor', 'hospital', 'pharmacy', 'pharmeasy', 'netmeds', '1mg'],
    merchantPatterns: ['apollo', 'pharmeasy', 'netmeds', '1mg', 'medplus', 'practo'],
    isSystem: true,
    isArchived: false,
    sortOrder: 12,
  },
  {
    id: generateId(),
    name: 'Health Insurance',
    type: CategoryType.EXPENSE,
    icon: '🛡️',
    color: '#C0392B',
    keywords: ['insurance', 'health insurance', 'mediclaim', '80d'],
    merchantPatterns: ['star health', 'hdfc ergo', 'icici lombard', 'max bupa', 'care health'],
    isSystem: true,
    isArchived: false,
    sortOrder: 13,
  },
  // Personal
  {
    id: generateId(),
    name: 'Personal Care',
    type: CategoryType.EXPENSE,
    icon: '💅',
    color: '#FD79A8',
    keywords: ['personal', 'salon', 'spa', 'haircut', 'grooming', 'beauty', 'cosmetics'],
    merchantPatterns: ['nykaa', 'purplle', 'mamaearth', 'wow', 'lakme'],
    isSystem: true,
    isArchived: false,
    sortOrder: 14,
  },
  {
    id: generateId(),
    name: 'Fitness & Sports',
    type: CategoryType.EXPENSE,
    icon: '🏋️',
    color: '#00B894',
    keywords: ['gym', 'fitness', 'sports', 'yoga', 'workout', 'cult', 'decathlon'],
    merchantPatterns: ['cult', 'gold gym', 'decathlon', 'fitness first'],
    isSystem: true,
    isArchived: false,
    sortOrder: 15,
  },
  // Entertainment
  {
    id: generateId(),
    name: 'Entertainment',
    type: CategoryType.EXPENSE,
    icon: '🎬',
    color: '#A29BFE',
    keywords: ['entertainment', 'movie', 'netflix', 'amazon prime', 'hotstar', 'spotify', 'youtube'],
    merchantPatterns: ['netflix', 'amazon prime', 'disney', 'hotstar', 'spotify', 'bookmyshow', 'pvr', 'inox'],
    isSystem: true,
    isArchived: false,
    sortOrder: 16,
  },
  {
    id: generateId(),
    name: 'Subscriptions',
    type: CategoryType.EXPENSE,
    icon: '📺',
    color: '#6C5CE7',
    keywords: ['subscription', 'netflix', 'prime', 'spotify', 'hotstar', 'youtube premium'],
    merchantPatterns: ['netflix', 'spotify', 'amazon prime', 'hotstar', 'youtube', 'apple'],
    isSystem: true,
    isArchived: false,
    sortOrder: 17,
  },
  // Education
  {
    id: generateId(),
    name: 'Education',
    type: CategoryType.EXPENSE,
    icon: '📚',
    color: '#74B9FF',
    keywords: ['education', 'school', 'college', 'tuition', 'books', 'course', 'udemy', 'coursera'],
    merchantPatterns: ['udemy', 'coursera', 'unacademy', 'byju', 'vedantu', 'amazon books'],
    isSystem: true,
    isArchived: false,
    sortOrder: 18,
  },
  {
    id: generateId(),
    name: "Children's Education",
    type: CategoryType.EXPENSE,
    icon: '🎒',
    color: '#0984E3',
    keywords: ['school fees', 'tuition', 'coaching', 'children', 'kids', 'school'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 19,
  },
  // Domestic
  {
    id: generateId(),
    name: 'Domestic Help',
    type: CategoryType.EXPENSE,
    icon: '🧹',
    color: '#636E72',
    keywords: ['maid', 'cook', 'driver', 'domestic', 'helper', 'nanny', 'watchman'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 20,
  },
  // Travel
  {
    id: generateId(),
    name: 'Travel & Vacation',
    type: CategoryType.EXPENSE,
    icon: '✈️',
    color: '#00CEC9',
    keywords: ['travel', 'vacation', 'holiday', 'flight', 'hotel', 'booking', 'makemytrip', 'goibibo'],
    merchantPatterns: ['makemytrip', 'goibibo', 'oyo', 'airbnb', 'cleartrip', 'ixigo', 'indigo', 'air india'],
    isSystem: true,
    isArchived: false,
    sortOrder: 21,
  },
  // Financial
  {
    id: generateId(),
    name: 'Insurance',
    type: CategoryType.EXPENSE,
    icon: '🔒',
    color: '#2D3436',
    keywords: ['insurance', 'life insurance', 'term', 'lic', 'premium'],
    merchantPatterns: ['lic', 'hdfc life', 'icici prudential', 'max life', 'sbi life'],
    isSystem: true,
    isArchived: false,
    sortOrder: 22,
  },
  {
    id: generateId(),
    name: 'Loan EMI',
    type: CategoryType.EXPENSE,
    icon: '🏦',
    color: '#B2BEC3',
    keywords: ['emi', 'loan', 'home loan', 'car loan', 'personal loan'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 23,
  },
  {
    id: generateId(),
    name: 'Bank Charges',
    type: CategoryType.EXPENSE,
    icon: '💳',
    color: '#DFE6E9',
    keywords: ['bank', 'charges', 'fees', 'atm', 'debit', 'credit card'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 24,
  },
  {
    id: generateId(),
    name: 'Credit Card Payment',
    type: CategoryType.EXPENSE,
    icon: '💳',
    color: '#5352ED',
    keywords: ['credit card', 'cc payment', 'card payment'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 25,
  },
  // Special
  {
    id: generateId(),
    name: 'Gifts & Donations',
    type: CategoryType.EXPENSE,
    icon: '🎁',
    color: '#FF7675',
    keywords: ['gift', 'donation', 'charity', 'present', 'birthday'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 26,
  },
  {
    id: generateId(),
    name: 'Festival & Celebrations',
    type: CategoryType.EXPENSE,
    icon: '🎉',
    color: '#FFEAA7',
    keywords: ['festival', 'diwali', 'holi', 'eid', 'christmas', 'celebration', 'party'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 27,
  },
  {
    id: generateId(),
    name: 'Gold & Jewelry',
    type: CategoryType.EXPENSE,
    icon: '💍',
    color: '#FFD700',
    keywords: ['gold', 'jewelry', 'jewellery', 'silver', 'ornament', 'tanishq', 'kalyan'],
    merchantPatterns: ['tanishq', 'kalyan', 'malabar', 'joyalukkas', 'pc jeweller'],
    isSystem: true,
    isArchived: false,
    sortOrder: 28,
  },
  {
    id: generateId(),
    name: 'Religious & Puja',
    type: CategoryType.EXPENSE,
    icon: '🪔',
    color: '#FF9F43',
    keywords: ['puja', 'religious', 'temple', 'mandir', 'church', 'mosque', 'gurudwara'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 29,
  },
  // Miscellaneous
  {
    id: generateId(),
    name: 'ATM Withdrawal',
    type: CategoryType.EXPENSE,
    icon: '🏧',
    color: '#636E72',
    keywords: ['atm', 'withdrawal', 'cash withdrawal'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 30,
  },
  {
    id: generateId(),
    name: 'Other Expenses',
    type: CategoryType.EXPENSE,
    icon: '📦',
    color: '#95A5A6',
    keywords: ['other', 'misc', 'miscellaneous'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 99,
  },
];

// ============================================
// Default Income Categories
// ============================================

export const defaultIncomeCategories: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  {
    id: generateId(),
    name: 'Salary',
    type: CategoryType.INCOME,
    icon: '💰',
    color: '#27AE60',
    keywords: ['salary', 'wages', 'payroll', 'income'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 1,
  },
  {
    id: generateId(),
    name: 'Freelance',
    type: CategoryType.INCOME,
    icon: '💻',
    color: '#2ECC71',
    keywords: ['freelance', 'consulting', 'contract', 'project'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 2,
  },
  {
    id: generateId(),
    name: 'Business',
    type: CategoryType.INCOME,
    icon: '🏪',
    color: '#1ABC9C',
    keywords: ['business', 'profit', 'revenue', 'sales'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 3,
  },
  {
    id: generateId(),
    name: 'Investment Returns',
    type: CategoryType.INCOME,
    icon: '📈',
    color: '#16A085',
    keywords: ['investment', 'dividend', 'interest', 'returns', 'capital gains'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 4,
  },
  {
    id: generateId(),
    name: 'Dividends',
    type: CategoryType.INCOME,
    icon: '💹',
    color: '#00B894',
    keywords: ['dividend', 'stock', 'mutual fund'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 5,
  },
  {
    id: generateId(),
    name: 'Interest Income',
    type: CategoryType.INCOME,
    icon: '🏦',
    color: '#00CEC9',
    keywords: ['interest', 'fd', 'fixed deposit', 'savings', 'rd'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 6,
  },
  {
    id: generateId(),
    name: 'Rental Income',
    type: CategoryType.INCOME,
    icon: '🏠',
    color: '#0984E3',
    keywords: ['rent', 'rental', 'tenant', 'property'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 7,
  },
  {
    id: generateId(),
    name: 'Bonus',
    type: CategoryType.INCOME,
    icon: '🎁',
    color: '#6C5CE7',
    keywords: ['bonus', 'incentive', 'reward', 'performance'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 8,
  },
  {
    id: generateId(),
    name: 'Cashback & Rewards',
    type: CategoryType.INCOME,
    icon: '🎯',
    color: '#A29BFE',
    keywords: ['cashback', 'reward', 'points', 'credit card reward'],
    merchantPatterns: ['cred', 'paytm', 'gpay', 'phonepe'],
    isSystem: true,
    isArchived: false,
    sortOrder: 9,
  },
  {
    id: generateId(),
    name: 'Gift Received',
    type: CategoryType.INCOME,
    icon: '🎀',
    color: '#FD79A8',
    keywords: ['gift', 'present', 'received'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 10,
  },
  {
    id: generateId(),
    name: 'Refund',
    type: CategoryType.INCOME,
    icon: '↩️',
    color: '#74B9FF',
    keywords: ['refund', 'return', 'reimbursement'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 11,
  },
  {
    id: generateId(),
    name: 'Tax Refund',
    type: CategoryType.INCOME,
    icon: '📋',
    color: '#00B894',
    keywords: ['tax refund', 'itr', 'income tax'],
    merchantPatterns: ['income tax', 'itr'],
    isSystem: true,
    isArchived: false,
    sortOrder: 12,
  },
  {
    id: generateId(),
    name: 'Sale Proceeds',
    type: CategoryType.INCOME,
    icon: '🏷️',
    color: '#FDCB6E',
    keywords: ['sale', 'sold', 'selling', 'olx', 'quikr'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 13,
  },
  {
    id: generateId(),
    name: 'Pension',
    type: CategoryType.INCOME,
    icon: '👴',
    color: '#636E72',
    keywords: ['pension', 'retirement', 'pf'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 14,
  },
  {
    id: generateId(),
    name: 'Other Income',
    type: CategoryType.INCOME,
    icon: '💵',
    color: '#95A5A6',
    keywords: ['other', 'misc', 'miscellaneous'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 99,
  },
];

// ============================================
// Default Transfer Categories
// ============================================

export const defaultTransferCategories: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  {
    id: generateId(),
    name: 'Account Transfer',
    type: CategoryType.TRANSFER,
    icon: '🔄',
    color: '#9B59B6',
    keywords: ['transfer', 'move', 'shift'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 1,
  },
  {
    id: generateId(),
    name: 'Investment',
    type: CategoryType.TRANSFER,
    icon: '📊',
    color: '#3498DB',
    keywords: ['invest', 'sip', 'mutual fund', 'stock'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 2,
  },
  {
    id: generateId(),
    name: 'Savings',
    type: CategoryType.TRANSFER,
    icon: '🐷',
    color: '#E91E63',
    keywords: ['savings', 'save', 'fd', 'rd'],
    merchantPatterns: [],
    isSystem: true,
    isArchived: false,
    sortOrder: 3,
  },
];

// ============================================
// All Default Categories
// ============================================

export const defaultCategories = [
  ...defaultExpenseCategories,
  ...defaultIncomeCategories,
  ...defaultTransferCategories,
];

// ============================================
// Default App Settings
// ============================================

export const defaultAppSettings: AppSettings = {
  id: 'app_settings',
  theme: 'system',
  language: 'en',
  defaultCurrency: 'INR',
  numberFormat: 'indian',
  dateFormat: 'dd/MM/yyyy',
  hideBalances: false,
  requireAuthOnLaunch: true,
  notificationsEnabled: true,
  emiReminders: true,
  budgetAlerts: true,
  dailyDigest: false,
  syncEnabled: false,
  onboardingCompleted: false,
  voiceEntryEnabled: true,
  ocrEnabled: true,
  aiInsightsEnabled: true,
};

// ============================================
// Sample Account Templates
// ============================================

export const accountTemplates = [
  // Banks
  { name: 'State Bank of India', icon: '🏦', color: '#1E4FA7', type: 'bank' },
  { name: 'HDFC Bank', icon: '🏦', color: '#004C8F', type: 'bank' },
  { name: 'ICICI Bank', icon: '🏦', color: '#B02A30', type: 'bank' },
  { name: 'Axis Bank', icon: '🏦', color: '#97144D', type: 'bank' },
  { name: 'Kotak Bank', icon: '🏦', color: '#ED1C24', type: 'bank' },
  { name: 'Yes Bank', icon: '🏦', color: '#0066B3', type: 'bank' },
  { name: 'IDFC First Bank', icon: '🏦', color: '#9C1C47', type: 'bank' },
  { name: 'IndusInd Bank', icon: '🏦', color: '#003366', type: 'bank' },
  { name: 'Punjab National Bank', icon: '🏦', color: '#0066B3', type: 'bank' },
  { name: 'Bank of Baroda', icon: '🏦', color: '#F15A22', type: 'bank' },
  { name: 'Canara Bank', icon: '🏦', color: '#FFD100', type: 'bank' },
  { name: 'Union Bank', icon: '🏦', color: '#004A8F', type: 'bank' },

  // Wallets
  { name: 'Paytm Wallet', icon: '📱', color: '#00BAF2', type: 'wallet' },
  { name: 'PhonePe Wallet', icon: '📱', color: '#5F259F', type: 'wallet' },
  { name: 'Amazon Pay', icon: '📱', color: '#FF9900', type: 'wallet' },
  { name: 'Mobikwik', icon: '📱', color: '#4A90D9', type: 'wallet' },
  { name: 'Freecharge', icon: '📱', color: '#6739B7', type: 'wallet' },

  // Cash
  { name: 'Cash', icon: '💵', color: '#27AE60', type: 'cash' },
  { name: 'Home Cash', icon: '🏠', color: '#2ECC71', type: 'cash' },

  // Credit Cards
  { name: 'HDFC Credit Card', icon: '💳', color: '#004C8F', type: 'credit_card' },
  { name: 'ICICI Credit Card', icon: '💳', color: '#B02A30', type: 'credit_card' },
  { name: 'SBI Credit Card', icon: '💳', color: '#1E4FA7', type: 'credit_card' },
  { name: 'Axis Credit Card', icon: '💳', color: '#97144D', type: 'credit_card' },
  { name: 'Kotak Credit Card', icon: '💳', color: '#ED1C24', type: 'credit_card' },
  { name: 'AMEX Card', icon: '💳', color: '#006FCF', type: 'credit_card' },
];

// ============================================
// Investment Brokers
// ============================================

export const investmentBrokers = [
  { name: 'Zerodha', icon: '📊', color: '#387ED1' },
  { name: 'Groww', icon: '📈', color: '#5367FF' },
  { name: 'Upstox', icon: '📉', color: '#8B5CF6' },
  { name: 'Angel One', icon: '📊', color: '#FF6B6B' },
  { name: 'ICICI Direct', icon: '📈', color: '#B02A30' },
  { name: 'HDFC Securities', icon: '📊', color: '#004C8F' },
  { name: 'Kotak Securities', icon: '📈', color: '#ED1C24' },
  { name: 'Paytm Money', icon: '📊', color: '#00BAF2' },
  { name: 'Kuvera', icon: '📈', color: '#4CAF50' },
  { name: 'ET Money', icon: '📊', color: '#FF5722' },
  { name: 'Coin by Zerodha', icon: '📈', color: '#387ED1' },
];

// ============================================
// Loan Lenders
// ============================================

export const loanLenders = [
  { name: 'State Bank of India', type: 'bank' },
  { name: 'HDFC Bank', type: 'bank' },
  { name: 'ICICI Bank', type: 'bank' },
  { name: 'Axis Bank', type: 'bank' },
  { name: 'Kotak Bank', type: 'bank' },
  { name: 'Punjab National Bank', type: 'bank' },
  { name: 'Bank of Baroda', type: 'bank' },
  { name: 'Canara Bank', type: 'bank' },
  { name: 'HDFC Ltd', type: 'nbfc' },
  { name: 'LIC Housing', type: 'nbfc' },
  { name: 'Bajaj Finserv', type: 'nbfc' },
  { name: 'Tata Capital', type: 'nbfc' },
  { name: 'L&T Finance', type: 'nbfc' },
  { name: 'Mahindra Finance', type: 'nbfc' },
];
